version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/public
      - ./database:/var/www/html/database
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
